### ISSUE TITLE
Incorrect orther for "-input=false -no-color" arguments

### ISSUE THREAD

**Issue by artberri** [XpiritBV/Xpirit-Vsts-Release-Terraform#9] opened 2018-04-17 18:35 UTC
Hi,

First of all, thank you for creating this task. To have the ability to install Terraform in the hosted agents is awesome!

There is an issue with the "-input=false -no-color" arguments that are being added to the terraform command. Right now, I think it is not possible to apply a terraform plan. Let check the command:

```
$ terraform apply -h
Usage: terraform apply [options] [DIR-OR-PLAN]
[...]
```

As you can see, the path to the plan to be executed should be at the end of the command line. But in the following line you are adding those arguments always at the end:

https://github.com/XpiritBV/Xpirit-Vsts-Release-Terraform/blob/master/Xpirit-Vsts-Release-Terraform/terraform.ps1#L149

When I want to execute `terraform apply my.plan` I add `apply my.plan` to the "Terraform arguments" field of the task, but what is actually being executed is `terraform apply my.plan -input=false -no-color` which throws an error. The proper unnatended command should be: `terraform apply -input=false -no-color my.plan`. You can check the error in the following log:

```
2018-04-17T18:19:02.6849925Z Terraform has been successfully initialized!
2018-04-17T18:19:02.6850121Z 
2018-04-17T18:19:02.6860217Z You may now begin working with Terraform. Try running "terraform plan" to see
2018-04-17T18:19:02.6862604Z any changes that are required for your infrastructure. All Terraform commands
2018-04-17T18:19:02.6866497Z should now work.
2018-04-17T18:19:02.6866705Z 
2018-04-17T18:19:02.6866978Z If you ever set or change modules or backend configuration for Terraform,
2018-04-17T18:19:02.6867431Z rerun this command to reinitialize your working directory. If you forget, other
2018-04-17T18:19:02.6875019Z commands will detect it and remind you to do so if necessary.
2018-04-17T18:19:03.0430209Z ##[command]"terraform" apply my.plan -input=false -no-color
2018-04-17T18:19:03.1192031Z Too many command line arguments. Configuration path expected.
2018-04-17T18:19:03.1336529Z ##[error] Terraform failed to execute. Error: 
2018-04-17T18:19:03.1348318Z End of Task Terraform
```

The only solution for this that I can think right now is to create a new field for arguments after options or to add the ability to ignore those extra arguments (being the user responsible of adding them on the command line).

What do you think?

Let me know also if I'm wrong and there is a way to do it but I missed it.

**Comment by mud5150** [comment] 2018-04-18 00:51
Ahh, I believe that's correct. I will update to fix this. I think the best thing to do, since the plan file always needs to be the last argument, is to add an input field for the plan file. I will try to get a PR in for this in the next few days.

**Comment by mud5150** [comment] 2018-04-18 02:01
@artberri A word of caution though with using plan files. I found it to be too difficult to manage using a plan file unless you're running plan and apply within the same process. If you use anything like file path variable expansion it will create the literal absolute path value when you create the plan file, so if you try to run apply and the workspace path for the agent is different the step will fail.

**Comment by artberri** [comment] 2018-04-18 06:52
Hey @mud5150 thank you for answering so fast!

I'll have caution, but I'm used to work with plans (I was doing it using CMD commands until your brilliant extension appears). The thing is that we are holding the deployment until manual approval and we don't want our code to be automatically executed if there has been some changes in our infrastructure after the build (during the 'on hold' time).

Anyway, I've been thinking about it. `terraform plan` is not the only command that allows extra parameters apart from the options. So, maybe a new field could solve my problem but will not solve the same problem with other commands.

What we can see as a pattern is this:

```
terraform [subcommand] [options] [other-params]]
```

Maybe you can parse the arguments field and extract the first word (which should be the terraform subcommand). I mean to split the arguments field between 'subcommand' and the 'rest of arguments', then, concatenate them in the following way:

```
terraform [subcommand] -input=false -no-color [rest-of-arguments]
```

I think this way should work for all terraform commands and not only for `terraform apply`.

Of course, this is only a possible advice, up to you to decide the best way.

Thanks in advance.

**Comment by mud5150** [comment] 2018-04-23 18:19
@artberri Starting to work on this today. I think for now I'll add a field for the plan file and append it to the end to support the [main automation workflow](https://www.terraform.io/guides/running-terraform-in-automation.html#automated-workflow-overview). If you have another command specifically that you're concerned with using let me know and I will take a look at that. 

I'm taking this opportunity to build out a small testing pipeline so it may take me a little longer to get this PR in.

**Comment by mud5150** [comment] 2018-04-24 15:31
@artberri If you can't wait for the update to be published you can install the latest from my branch using [tfx cli](https://github.com/Microsoft/tfs-cli)  
Running `tfx build tasks upload --task-path .\Xpirit-Vsts-Release-Terraform\` from the root of the repo will update it for you.

**Comment by artberri** [comment] 2018-05-14 12:23
Thank you!! I'll try to test it ASAP ;)

**Comment by grantwar** [comment] 2018-05-31 14:12
@mud5150 I'm having a similar issue with the "-input=false -no-color" arguments that are being added to the terraform command, which is manifesting itself in the init command.
In actual fact the init succeeds, and my subsequent apply is completed without any issues at all, however the VSTS task fails due to the init error. While I can set "continue on error=true" at the task level, I still believe this shouldn't be added to the init command.

Steps to reproduce:
I'm using my own _backend.tf azurerm template preconfigured.
VSTS terraform apply task
Azure Connection Type = Azure Resource Manager
Init state in Azure storage = true
Specify Storage Account = false
Additional Terraform Init arguments = "dv01-platform" (the name of the tfstate blob - different for each environment).

VSTS log Error:
2018-05-31T13:33:59.3425373Z ##[command]"terraform" init -backend-config="arm_subscription_id=***" -backend-config="arm_tenant_id=***" -backend-config="arm_client_id=***" -backend-config="arm_client_secret=***" dv01-platform -input=false -no-color
2018-05-31T13:33:59.4288762Z The init command expects at most one argument.

**Comment by mud5150** [comment] 2018-05-31 14:23
@grantwar Am I correct in understanding this is the path to your state file? If so I would expect something like `-backend-config="path=dv01-platform"` to be the additional argument. Let me know if that helps.

**Comment by grantwar** [comment] 2018-05-31 14:53
@mud5150 I've given that a go, however I don't believe that is correct - path is not a valid configuration variable for [azurerm backend](https://www.terraform.io/docs/backends/types/azurerm.html).
I've looked at the source and can see that the default arguments are being appended regardless of if there are additional arguments or not.

```
$additionalArguments = Get-VstsInput -Name InitArguments
    if (-not ([string]::IsNullOrEmpty($additionalArguments)))
    {
        $arguments = $remoteStateArguments + " $($additionalArguments.Trim()) -input=false -no-color"
    } else {
        $arguments = $remoteStateArguments + " -input=false -no-color"
    }
```

I tried to fix the issue in a branch and raise a PR, however I've not got permissions to do so.

**Comment by mud5150** [comment] 2018-05-31 15:06
@grantwar It looks like `key` would be analogous to `path` for the azurerm backend so the argument would be `-backend-config="key=dv01-platform"` if dv01-platform is the name of the file blob in the storage account. If that still doesn't work I would recommend getting a working parameter set running locally and then you should be able to replicate that in the build step. If you can get something working locally and can't get the build step to reproduce this functionality send me the local command and the output. 

Those additional arguments are intended to always be there and are recommended by the Terraform automation documentation. I believe the issue is just about getting the parameter correct that will allow you to specify the state file path.

If you did need to submit a PR you can fork the repo and submit a PR from the fork.

**Comment by grantwar** [comment] 2018-05-31 15:37
@mud5150 I've been running it locally and can confirm that key does indeed work. The VSTS job now also works. Thanks for the prompt responses.

**Comment by artberri** [comment] 2018-06-05 13:33
The issue I reported here is already fixed (thanks @mud5150 ! ). I was going to close the issue, what do you think @grantwar ? It's your problem fixed or do you prefer me to keep it opened until you make that PR?

**Comment by pgroene** [comment] 2018-06-05 14:10
@artberri best is to close the issue when the pr is merged and I created a new release.

**Comment by grantwar** [comment] 2018-06-05 14:36
@artberri issue is fixed using `-backend-config="key=dv01-platform"`. Thanks for the prompt responses.

**Comment by mud5150** [comment] 2018-06-12 01:04
@pgroene Feel free to add me as an outside collaborator if that would be helpful for getting issues closed.

**Closed as completed** 2018-06-13 12:13 UTC

**Comment by mud5150** [comment] 2018-06-13 12:15
Resolved by [this commit](https://github.com/XpiritBV/Xpirit-Vsts-Release-Terraform/commit/8f4f0af5c2e92cc8f27766ed048a8deb47731045)
